[project]
name = "sprint"
version = "0.1.0"
description = "IDE Series 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "p5>=0.7.1",
    "pybricks>=3.6.0",
    "pybricksdev>=1.0.1",
    "pytest>=8.3.5",
]
